# Generated by Django 3.2.6 on 2021-08-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rareuser',
            name='profile_img',
        ),
        migrations.AddField(
            model_name='rareuser',
            name='profile_image_url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
