# Generated by Django 3.2.6 on 2021-08-17 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_auto_20210817_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rareuser',
            name='active',
        ),
        migrations.RemoveField(
            model_name='rareuser',
            name='created_on',
        ),
    ]
